# Generated by Django 4.0.4 on 2022-05-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PromoBot', '0002_remove_store_category_storecategory_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecategory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storecategory',
            name='url',
        ),
        migrations.CreateModel(
            name='StoreCategoryURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PromoBot.storecategory')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PromoBot.store')),
            ],
        ),
    ]
