# Generated by Django 4.0.4 on 2022-05-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromoBot', '0004_storecategory_available_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
