# Generated by Django 4.0.4 on 2022-06-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromoBot', '0007_promo_promocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='certain',
            field=models.BooleanField(default=True),
        ),
    ]
