# Generated by Django 4.0.5 on 2022-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromoBot', '0011_alter_thumbnail_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
