# Generated by Django 4.0.4 on 2022-05-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0002_rename_cateogry_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
