# Generated by Django 4.0.4 on 2022-05-15 20:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0003_alter_userdata_promobot_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='promobot_api_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='telegram_api_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
