# Generated by Django 4.0.4 on 2022-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0003_rename_category_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url', models.URLField(unique=True)),
                ('photo_url', models.URLField(max_length=300)),
            ],
        ),
    ]
