# Generated by Django 4.0.4 on 2022-05-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0004_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.JSONField(default=None),
        ),
    ]
