# Generated by Django 4.0.4 on 2022-05-15 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0005_remove_userdata_id_alter_userdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producturls',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='priceBot.product'),
        ),
    ]
