# Generated by Django 4.0.4 on 2022-05-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0006_alter_store_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='tags',
            field=models.CharField(max_length=300),
        ),
    ]
