# Generated by Django 4.0.4 on 2022-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0007_alter_userdata_promobot_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='promobot_api_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
