# Generated by Django 4.0.4 on 2022-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0008_alter_userdata_promobot_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
            ],
        ),
    ]
