# Generated by Django 4.0.4 on 2022-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0009_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='token',
            field=models.BinaryField(blank=True),
        ),
    ]
