# Generated by Django 4.0.4 on 2022-05-18 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0010_userdata_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lowest_price_date', models.DateTimeField(auto_now=True)),
                ('last_check_date', models.DateTimeField(auto_now=True)),
                ('last_check_lowest_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_check_lowest_price_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowest_price_last_check_store', to='priceBot.store')),
                ('lowest_price_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowest_price_so_far_store', to='priceBot.store')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='priceBot.product')),
            ],
        ),
    ]
