# Generated by Django 4.0.4 on 2022-05-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0011_productstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_version', models.FileField(upload_to='releases/')),
                ('linux_version', models.FileField(upload_to='releases/')),
                ('mac_version', models.FileField(upload_to='releases/')),
            ],
        ),
    ]
