# Generated by Django 4.0.4 on 2022-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0012_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
