# Generated by Django 4.0.4 on 2022-05-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceBot', '0016_remove_store_category_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='priceBot.storecategory'),
        ),
    ]
